version: '3.0'
services: 
  db:
    image: postgres:12-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: gary
      POSTGRES_USER: gary
      POSTGRES_PASSWORD: garysdevil
      PGDATA: /var/lib/postgresql/data/pgdata
    # volumes:
    #   - ../pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  backend:
    environment:
      - TZ=Asia/Shanghai
    restart: on-failure:10
    build:
      context: .
      dockerfile: ./prod.Dockerfile
    ports:
      - 801:801
    volumes: 
      - .:/srv/Location_backend/a
    depends_on:
      - db

