version: '3.0'
services: 
  rabbitmq:
    restart: on-failure:10
    image: rabbitmq:3.7-management
    environment:
      RABBITMQ_DEFAULT_USER: "gary"
      RABBITMQ_DEFAULT_PASS: "gary"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
       - "15672:15672"
       - "5672:5672"
  db:
    image: postgres:12-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: gary
      POSTGRES_USER: gary
      POSTGRES_PASSWORD: garysdevil
      PGDATA: /var/lib/postgresql/data/pgdata
    # volumes:
    #   - ../pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  backend:
    environment:
      - TZ=Asia/Shanghai
    restart: on-failure:10
    image: node:12.4.0-alpine
    ports:
      - 801:801
    working_dir: /srv/Location_backend
    volumes: 
      - .:/srv/Location_backend
    depends_on:
      - db
    command: npm run start

